name: geodata_in_python
channels:
- conda-forge
- defaults
dependencies:
- python=3.12.0
- numpy=1.26.0 
- shapely=2.0.2
- fiona=1.9.5
- affine=2.4.0
- rasterio=1.3.8
- geopandas=0.14.0
- matplotlib=3.8.0
- jupyter=1.0.0
- jupyterlab=4.0.7
